# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: make
      uses: GabrielBB/xvfb-action@v1
      with:
        run: make
    - run: |
        mkdir parsegraph-spotlightpainter
        cp -r -t parsegraph-spotlightpainter package.json package-lock.json README.md demo/ LICENSE dist/
        tar cvzf parsegraph-spotlightpainter.tar.gz parsegraph-spotlightpainter/
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-spotlightpainter-${{ github.run_number }}
        path: parsegraph-spotlightpainter.tar.gz
